import '../styles/globals.css'
import {Navigation} from './components/Navegation';
import {UserProvider} from "./components/Context/UserContextProvider";

export const metadata = {
  title: 'Poke-Api',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">             
      <body>
      <UserProvider>
          <Navigation/>
          {children}
      </UserProvider>
      </body>
    </html>
  )
}
